### ISSUE TITLE
WooCommerce product blocks don't respect number of columns

### ISSUE THREAD

**Issue by helgatheviking** [godaddy-wordpress/go#581] opened 2020-09-07 19:00 UTC
**Describe the bug:**
WooCommerce hand-picked products block set to 3 columns shows 2 columns at large sizes. This appears to be because
the `@media (min-width:960px)` media queries come _before_ `@media (min-width:600px)` media queries in the `style-shared.css` file and so the 600px width queries take precedence.

**Screenshot (current):**
![image](https://user-images.githubusercontent.com/507025/92412529-6c2b5400-f109-11ea-8405-cc3c301e7fc1.png)

**Screenshot (expected):**
![image](https://user-images.githubusercontent.com/507025/92412551-8107e780-f109-11ea-80f0-2133a1718697.png)

**Comment by jrtashjian** [comment] 2021-12-16 20:55
Closing as I am unable to reproduce this issue.

**Closed by jrtashjian** 2021-12-16 20:55 UTC
