### ISSUE TITLE
Four menu locations, I only see two. 

### ISSUE THREAD

**Issue by nickhamze** [godaddy-wordpress/go#443] opened 2020-01-17 15:16 UTC
**Describe the bug:**
When I go to set my menus it says I have four menu locations to choose from but I only see two. It looks like two more are added when you change the footer layout but it is confusing until you find that out. 

**Screenshot(s):**
<img width="296" alt="Screen Shot 2020-01-17 at 9 11 34 AM" src="https://user-images.githubusercontent.com/158918/72622864-b60cc300-3909-11ea-8bbb-6e2d92f85174.png">

**Priority** (select one):
- [ ] High - Functional blocker
- [ ] Medium - Doesn't work as expected 
- [x] Low - Not a big deal but we'd want to get to this eventually

**Comment by richtabor** [comment] 2020-01-17 16:18
The footer menu count is actually dependent on the footer variation selected within the **Customizer > Footer panel**. For example, if you're using a footer layout with multiple menus, it'll show those menu options here - but if you have a footer layout with just one menu, you'll see just one option here.

<img width="1432" alt="Screen Shot 2020-01-17 at 11 15 36 AM" src="https://user-images.githubusercontent.com/1813435/72627569-b95c7a80-391a-11ea-8fe4-10ff0be012c5.png">

I wonder if we can update the menu count numeral to the value enabled by the footer variation. Not sure how doable that is. Thoughts @EvanHerman?

**Comment by nickhamze** [comment] 2020-01-17 16:31
Oh, it looks like you are hiding them with CSS instead of unhooking them. 

So 4 areas are always there you just don't show them all unless the setting uses it.

**Comment by richtabor** [comment] 2020-01-17 16:32
We're hiding them within the Customizer using CSS, though we're hooking to the controls to determine which are available. We may be able to do something with that integer though.

**Comment by nickhamze** [comment] 2020-01-17 16:37
Also if you go Appearance -> Menus it will show all four regardless of the setting in the customizer. Can't you just deregister the menus that aren't needed when the setting is changed.

**Comment by richtabor** [comment] 2020-01-17 16:48
> Can't you just deregister the menus that aren't needed when the setting is changed.

As long as they're re-registered as soon as the footer variation is enabled (so they can be manipulated live).

**Comment by nickhamze** [comment] 2020-01-17 16:54
Yeah I have no clue if that's possible, this stuff is way over my head :) .

I'm stuck at home during a blizzard and dying of boredom. Hopefully one of my developers can ship some blocks today and I'll stop pestering people on GitHub. I'll be lurking for a while now and finally got bored enough to post.

**Comment by EvanHerman** [comment] 2020-01-21 18:48
@nickhamze In short, we can't deregister the settings because they are registered in PHP, on initial load of the customizer. We can't register the settings once the customizer has loaded, which is why we conditionally show/hide those settings with JS.

In the PR I've pushed up (#445) I've implemented some work in our JS file to update that string based on the currently selected footer variation. We should be able to get some testing done and get this merged in to the next release.

Thanks for taking the time to report the issue and outlining the steps to reproduce! 👍

**Comment by nickhamze** [comment] 2020-01-21 20:47
I really should stop wasting your time :) but I'm so curious on why you decided on three separate footer widget areas instead of one area where the layout changes with CSS based on which footer variation they choose.

**Comment by richtabor** [comment] 2020-01-22 12:17
> ...I'm so curious on why you decided on three separate footer widget areas instead of one area where the layout changes with CSS based on which footer variation they choose.

I almost went that route, though there were too many additions, not just layout changes, across the different variations. Some with more menus than others, social in very different positions, some with the site logo added in the footer. And on top of that, it makes modifying variations to suite ones' needs easier if they "templated" in nature. :)

**Closed** 2020-01-28 21:46 UTC
Labels: customizer
